# Generated by Django 6.1.1 on 2026-09-30 00:08

import analytics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(default=analytics.models.generate_api_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinct_id', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='analytics.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'distinct_id'), name='unique_person_per_project')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('distinct_id', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'event', 'timestamp'], name='analytics_e_project_727df4_idx'), models.Index(fields=['project', 'distinct_id', 'timestamp'], name='analytics_e_project_c3fed1_idx')],
            },
        ),
    ]
